<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Jellyfin.Plugin.MediaCccDe</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.MediaCccDe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.*" />
    <PackageReference Include="Jellyfin.Model" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Compile Remove="Services\UserLibraryService.cs" />
    <Compile Remove="Services\IUserLibraryService.cs" />
    <Compile Remove="Services\DownloadService.cs" />
    <Compile Remove="Services\FileService.cs" />
    <Compile Remove="Services\IFileService.cs" />
    <Compile Remove="ServiceRegistrator.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\**\*.html" />
    <EmbeddedResource Include="Pages\**\*.html" />
    <EmbeddedResource Include="Pages\**\*.js" />
    <EmbeddedResource Include="Controllers\**\*.js" />
  </ItemGroup>

</Project>
