<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Jellyfin.Plugin.MediaCccDe</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.MediaCccDe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\**\*.html" />
    <EmbeddedResource Include="Pages\**\*.html" />
    <EmbeddedResource Include="Pages\**\*.js" />
    <EmbeddedResource Include="Controllers\**\*.js" />
  </ItemGroup>

</Project>
