<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.*" />
    <PackageReference Include="Jellyfin.Model" Version="10.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Unit/DownloadProcessingTests.cs" />
    <Compile Remove="Unit/FileServiceTests.cs" />
    <Compile Remove="Unit/UserLibraryServiceTests.cs" />
    <Compile Remove="Unit/ServiceRegistratorTests.cs" />
    <Compile Remove="Unit/UserDataManagerTests.cs" />
    <Compile Remove="Unit/MediaCccEpisodeProviderTests.cs" />
    <Compile Remove="Integration/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jellyfin.Plugin.MediaCccDe.csproj" />
  </ItemGroup>

</Project>